name:                Ash
version:             0.1.0.0
github:              "alexanderjdupree/Ash"
license:             BSD3
author:              "Alexander DuPree"
maintainer:          "alexander.j.dupree@gmail.com"
copyright:           "Copyright Alexander DuPree (c) 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexanderjdupree/Ash#readme>

dependencies:
- base >= 4.7 && < 5
- text
- process
- directory

library:
  source-dirs: Ash

executables:
  Ash:
    main:                Main.hs
    source-dirs:         Ash
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Ash

tests:
  Ash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Ash
    - hspec
    - QuickCheck

